import { TravelPackage } from "../types";
import Peru from "@/assets/travel/peru.webp";
import Holand from "@/assets/travel/holand.webp";
import DesertoDoSaara from "@/assets/travel/deserto-do-saara.webp";
import Istambul from "@/assets/travel/Istambul.webp";

const gruposComGuia: TravelPackage[] = [
  {
    id: 1,
    image: Peru,
    title: "Peru: Machu Picchu & Vale Sagrado",
    location: "Peru, América do Sul",
    departureLocation: "São Paulo (GRU)",
    days: 7,
    taxes: ["Inclusas"],
    fullPrice: 13260,
    parcelPrice: 884,
    parcelTimes: 15,
    description: [
      "🗺️ Lima, Cusco, Vale Sagrado e Machu Picchu",
      "✈️ Passagem aérea com LATAM",
      "🚍 Transfers inclusos",
      "☕ Café da manhã diário",
      "🏛️ City tour em Lima Moderna e Colonial, Cusco e ruínas próximas",
      "🌄 Visitas a Moray, Maras, Feira de Pisac e Fortaleza de Ollantaytambo",
      "🎟️ Tour guiado em Machu Picchu",
      "🛡️ Protect Travel (Cobertura de cancelamento até R$ 16.000)",
      "📆 Saída de 28/04 a 04/05",
    ],
  },
  {
    id: 2,
    image: Holand,
    title: "Holand Florida",
    location: "Belgica e França",
    departureLocation: "São Paulo (GRU)",
    days: 15,
    taxes: ["Inclusas"],
    fullPrice: 32790,
    parcelPrice: 2186,
    parcelTimes: 15,
    description: [
      "🗺️ Amsterdam, Antuérpia, Bruxelas, Bruges, Gante, Reims, Versalhes, Giverny, Paris",
      "✈️ Passagem aérea com Air France",
      "🚍 Transfers inclusos",
      "🏨 Hospedagem com café da manhã",
      "🏰 Visitas aos castelos Chenonceau e Chambord",
      "🌸 Visita ao Parque Keukenhof",
      "🎭 Passeios panorâmicos por Paris",
      "🎨 Visitas aos Jardins de Giverny e Rijksmuseum",
      "🛡️ Protect Travel (Cobertura até R$ 30.000)",
      "🎁 Mala de bordo personalizada para os 30 primeiros passageiros",
      "📆 Saída de 16 a 30/04",
    ],
  },
  {
    id: 3,
    image: DesertoDoSaara,
    title: "Deserto do Saara e Cidade Azul",
    location: "Marrocos, África",
    departureLocation: "São Paulo (GRU)",
    days: 12,
    taxes: ["Inclusas"],
    fullPrice: 20190,
    parcelPrice: 1346,
    parcelTimes: 15,
    description: [
      "🗺️ Casablanca, Rabat, Chefchaouen, Meknes, Volubilis, Midelt, Erfoud, Fez, Merzouga, Ouarzazate, Marrakech",
      "✈️ Passagem aérea com Royal Air Maroc",
      "🏨 Hospedagem com meia pensão (exceto no Saara)",
      "🚍 Transfers inclusos",
      "🏕️ Noite no Deserto do Saara em tendas de luxo",
      "🌆 1 Noite em Chefchaouen (Cidade Azul)",
      "🚙 Transporte em veículos 4x4",
      "🍽️ Jantar temático no restaurante Chez Ali",
      "🐪 Passeio de camelo pelas dunas do Saara",
      "🍛 Almoço especial em Marrakech",
      "🌿 Visita ao Jardim Majorelle",
      "🎁 Mala de bordo personalizada para os 30 primeiros passageiros",
    ],
  },
  {
    id: 4,
    image: Istambul,
    title: "Istambul, Capadócia & Riviera Turca",
    location: "Turquia, Europa",
    departureLocation: "São Paulo (GRU)",
    days: 11,
    taxes: ["Inclusas"],
    fullPrice: 15315,
    parcelPrice: 1021,
    parcelTimes: 15,
    description: [
      "🗺️ Istambul, Capadócia, Pamukkale, Éfeso, Kusadasi, Bursa",
      "✈️ Passagem aérea com Turkish Airlines",
      "🏨 4 noites em Istambul com café da manhã",
      "🏨 2 noites na Capadócia, 2 noites em Pamukkale e 2 noites em Kusadasi com café da manhã e jantar",
      "🚍 Transfers inclusos",
      "🏛️ Passeios guiados em diversos pontos turísticos",
      "📆 Saída de 14 a 24/04",
    ],
  },
];

export default gruposComGuia;
