import { TravelPackage } from "../types";
import Alemanha from "@/assets/travel/alemanha.webp";
import Bariloche from "@/assets/travel/bariloche.webp";
import Cartagena from "@/assets/travel/cartagena.webp";
import HardRockHotel from "@/assets/travel/hard-rock-hotel-cancun.webp";
import HardRockHotelLosCabos from "@/assets/travel/hard-rock-hotel-los-cabos.webp";
import HardRockHotelRivieraMaya from "@/assets/travel/hard-rock-hotel-riviera-maya.webp";
import Panama from "@/assets/travel/panama.webp";
import Turquia from "@/assets/travel/turquia.webp";
import Unico2087Hotel from "@/assets/travel/unico-2087-hotel.webp";

const pacotesInternacionais: TravelPackage[] = [
  {
    id: 1,
    image: HardRockHotel,
    title: "Hard Rock Hotel, All Inclusive",
    location: "Cancún, México",
    departureLocation: "Origem Não Especificada",
    days: 5,
    taxes: ["Inclusas"],
    fullPrice: 6075,
    parcelPrice: 405,
    parcelTimes: 15,
    description: ["🏨 Hospedagem de 18 a 22/06", "🍽️ Pacote All Inclusive", "🌴 Resort 5 estrelas", "💎 Luxo e conforto garantidos"],
  },
  {
    id: 2,
    image: HardRockHotelRivieraMaya,
    title: "Hard Rock Hotel, All Inclusive",
    location: "Riviera Maya, México",
    departureLocation: "Origem Não Especificada",
    days: 5,
    taxes: ["Inclusas"],
    fullPrice: 5205,
    parcelPrice: 347,
    parcelTimes: 15,
    description: ["🏨 Hospedagem de 18 a 22/06", "🍽️ Pacote All Inclusive", "🌊 Praia paradisíaca", "🎸 Experiência exclusiva Hard Rock"],
  },
  {
    id: 3,
    image: Unico2087Hotel,
    title: "UNICO 20° 87° Hotel",
    location: "Riviera Maya, México",
    departureLocation: "Origem Não Especificada",
    days: 5,
    taxes: ["Inclusas"],
    fullPrice: 7905,
    parcelPrice: 527,
    parcelTimes: 15,
    description: ["🏨 Hospedagem de 18 a 22/06", "🍽️ Pacote All Inclusive", "💆 Spa e relaxamento", "🌴 Experiência exclusiva de luxo"],
  },
  {
    id: 4,
    image: HardRockHotelLosCabos,
    title: "Hard Rock Hotel",
    location: "Los Cabos, México",
    departureLocation: "Origem Não Especificada",
    days: 5,
    taxes: ["Inclusas"],
    fullPrice: 7245,
    parcelPrice: 483,
    parcelTimes: 15,
    description: ["🏨 Hospedagem de 18 a 22/06", "🍽️ Pacote All Inclusive", "🌅 Vista incrível para o mar", "🎶 Experiência musical única"],
  },
  {
    id: 5,
    image: Alemanha,
    title: "Tour pela Alemanha",
    location: "voce escolhe a cidade",
    departureLocation: "Origem Não Especificada",
    days: 13,
    taxes: ["Inclusas"],
    fullPrice: 22005,
    parcelPrice: 1467,
    parcelTimes: 15,
    description: [
      "🚍 Transfer incluso",
      "🏨 Hospedagem com café da manhã",
      "🚢 Passeio de barco pelo rio Reno",
      "🏰 Entrada nos Castelos de Heidelberg, Neuschwanstein e Sanssouci",
      "🐄 Visita à fazenda na Floresta Negra com degustação de queijos",
      "📆 Saída de 21/04 a 03/05",
    ],
  },
  {
    id: 6,
    image: Panama,
    title: "Cidade do Panamá",
    location: "Cidade do Panamá, Panamá",
    departureLocation: "São Paulo (GRU)",
    days: 5,
    taxes: ["Inclusas"],
    fullPrice: 4875,
    parcelPrice: 325,
    parcelTimes: 15,
    description: [
      "✈️ Passagem aérea pela Copa Airlines",
      "🏨 Hospedagem no Hotel El Panamá by Faranda Grand",
      "🚍 Transfers inclusos",
      "☕ Café da manhã incluso",
      "🛳️ Tour pelo Canal do Panamá",
      "📆 Saída de 14 a 18/06",
    ],
  },
  {
    id: 7,
    image: Cartagena, 
    title: "Hotel Caribe - Pacote Completo",
    location: "Cartagena, Colômbia",
    departureLocation: "São Paulo (GRU)",
    days: 7,
    taxes: ["Inclusas"],
    fullPrice: 6570,
    parcelPrice: 438,
    parcelTimes: 15,
    description: [
      "✈️ Passagem aérea com Avianca",
      "🏨 Hospedagem no Hotel Caribe",
      "🚍 Transfers inclusos",
      "☕ Café da manhã incluso",
      "🚌 City tour em Chiva",
      "🛡️ Protect Travel (Cobertura até R$ 8 mil)",
      "📆 Saída de 07 a 13/06",
    ],
  },
  {
    id: 8,
    image: Bariloche,
    title: "Bariloche - Temporada de Neve",
    location: "Bariloche, Argentina",
    departureLocation: "São Paulo (GRU)",
    days: 6,
    taxes: ["Inclusas"],
    fullPrice: 6480,
    parcelPrice: 432,
    parcelTimes: 15,
    description: [
      "✈️ Passagem aérea com LATAM",
      "🏨 Hospedagem no Soft Bariloche Hotel",
      "🚍 Transfers inclusos",
      "❄️ Circuito Chico + Cerro Catedral (sem ingresso)",
      "📆 Saída de 24/06 a 29/06",
      "📆 Outra opção de saída: 03/07",
    ],
  },
  {
    id: 9,
    image: Turquia,
    title: "Turquia",
    location: "Turquia",
    departureLocation: "São Paulo (GRU)",
    days: 11,
    taxes: ["Inclusas"],
    fullPrice: 11235,
    parcelPrice: 749,
    parcelTimes: 15,
    description: [
      "✈️ Passagem aérea com Turkish Airlines",
      "🏨 4 noites em Istambul com café da manhã",
      "🏨 2 noites na Capadócia, 2 noites em Pamukkale e 2 noites em Kusadasi com café da manhã e jantar",
      "🚍 Transfers inclusos",
      "🏛️ Visitas ao Mausoléu de Ataturk, Göreme, Pamukkale e Hierápolis",
      "🗣️ Guia no destino falando português",
      "🛡️ Protect Travel (Cobertura até R$ 20 mil)",
      "📆 Últimos 5 lugares! Saída de 10 a 20/03",
    ],
  },
];

export default pacotesInternacionais;
